# Azure Web App Deployment - Fixed Build Process
name: Deploy to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies (including dev dependencies)
      run: |
        npm ci
        echo "Installed packages successfully"
        npx vite --version
        npx esbuild --version

    - name: Build application
      run: |
        echo "Starting build process..."
        npm run build
        echo "Build completed successfully"
        echo "Checking build outputs:"
        ls -la dist/
        ls -la dist/public/

    - name: Login to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7B06DFB09E9248A1977375A2542F4338 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CB6692794B84478D8D4A9C0DEBBE556A }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D97080276912466B96634E786DD2D9BF }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'Zheck'
        slot-name: 'Production'
        package: '.'

    - name: Verify deployment
      run: |
        echo "Deployment completed"
        echo "App should be available at: https://zheck.azurewebsites.net"